import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

import { Header } from "@/components/ui/Header";

const poppins = Poppins({
  weight: ["300", "400", "500", "700", "900"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased overflow-hidden`}>
        <div className="min-h-screen bg-gray-50 p-8">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
